name: ivanpereznunez
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030104'
    - '#191919'
    - '#705131'
    - '#916c4a'
    - '#a6825a'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
