name: ivanpereznunez
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffbe9'
    - '#7d593d'
    - '#ddc899'
    - '#8a956c'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
