name: ivanpereznunez
favicon: null
layout_spectrum: 0.86501908977516
typography_spectrum: 0.09123246022500098
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15634413226507604
  lightness: 0.8633070969954133
  saturation: 0.2790558740962297
  rhythmicContrast: 0.5583085515536368
purpose: []
