name: ivanpereznunez
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#515151'
    - '#fddccb'
    - '#9f8f75'
    - '#7e1405'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
